image: lorisleiva/laravel-docker:latest

stages:
  - build
  - test
  - deploy

composer:
  stage: build
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

npm:
  stage: build
  script:
      - npm install
      - npm run production
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - phpunit --coverage-text --colors=never

codestyle:
  stage: test
  dependencies: 
    - composer
  script:
    - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app

staging:
  stage: deploy
  script:
    - heroku container:push web
  environment:
    name: staging
    url: https://codersparaphernalia-staging.herokuapp.com
  only:
    - master

production:
  stage: deploy
  script:
    - heroku container:login
    - heroku create
    - heroku container:push web
    - heroku container:release web
  environment:
    name: production
    url: https://codersparaphernalia.herokuapp.com
  when: manual
  only:
   - master
