version: "3.1"
services:

    mysql:
      image: mysql:8
      container_name: coders-mysql
      working_dir: /application
      volumes:
        - .:/application
      command:
        - "--default-authentication-plugin=mysql_native_password"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: codersparaphernalia
      ports:
       - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: coders-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      ports:
       - "80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: coders-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:cached

    redis:
      image: redis:alpine
      container_name: coders-redis
