version: '3'

services:

    laravel:
      image: laravel:latest
      build:
        context: .
        args:
          - "BUILD_ARGUMENT_ENV=dev"
          - "BUILD_ARGUMENT_DEBUG_ENABLED=true"
        dockerfile: ./Dockerfile
      container_name: laravel
      expose:
        - "80"
        - "443"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/var/www/html
      depends_on:
        - db
      links:
        - db

    db:
      image: postgres:latest
      restart: unless-stopped
      tty: true
      container_name: coders-postgres
      ports:
        - "5432:5432"
